// In a file, e.g., person.dart
import 'package:hive/hive.dart';

part 'user_information_hive.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class User extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  String imgUrl;

  @HiveField(2)
  String gender;

  @HiveField(3)
  String ageGroup;

  @HiveField(4)
  String primaryHealthGoal;

  @HiveField(5)
  String fitnessGoal;

  @HiveField(6)
  String additionalNotes;

  @HiveField(7)
  String fitnessLevel;

  @HiveField(8)
  String exerciseStatus;

  @HiveField(9)
  String exerciseFrequency;


  User({
    required this.name,
    this.imgUrl = '',
    required this.gender,
    required this.ageGroup,
    required this.primaryHealthGoal,
    required this.fitnessGoal,
    this.additionalNotes = '',
    this.fitnessLevel = '',
    required this.exerciseStatus,
    this.exerciseFrequency = '',
  });

  @override
  String toString() => 'User(name: $name, gender: $gender, ageGroup: $ageGroup)';

  // Convert from UserData model to Hive model
  static User fromUserData(dynamic userData) {
    return User(
      name: userData.name,
      imgUrl: userData.imgUrl,
      gender: userData.gender,
      ageGroup: userData.ageGroup,
      primaryHealthGoal: userData.primaryHealthGoal,
      fitnessGoal: userData.fitnessGoal,
      additionalNotes: userData.additionalNotes,
      fitnessLevel: userData.fitnessLevel,
      exerciseStatus: userData.exerciseStatus,
      exerciseFrequency: userData.exerciseFrequency,
    );
  }

  // Convert to Map for easier serialization if needed
  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'imgUrl': imgUrl,
      'gender': gender,
      'ageGroup': ageGroup,
      'primaryHealthGoal': primaryHealthGoal,
      'fitnessGoal': fitnessGoal,
      'additionalNotes': additionalNotes,
      'fitnessLevel': fitnessLevel,
      'exerciseStatus': exerciseStatus,
      'exerciseFrequency': exerciseFrequency,
    };
  }
}
